export const popularItems = [
  {
    id: 1,
    imgurl: "/Trevland/image/loc-turkey.png",
    imgalt: "Воздушные шары над Каппадокией",
    title: "Istanbul, Turkey",
    text: "Istanbul is a major city in Turkey that straddles Europe. ",
  },
  {
    id: 2,
    imgurl: "/Trevland/image/loc-korea.png",
    imgalt: "фото Южной Кореи",
    title: "Seoul, South Korea",
    text: "South Korea officially the Republic of Korea is a country in East Asia.",
  },
  {
    id: 3,
    imgurl: "/Trevland/image/loc-malaysia.png",
    imgalt: "Золотая статуя на фоне гор",
    title: "Kuala Lumpur, malaysia",
    text: "A 272-step long trek leads you to this century.",
  },
];

export const specialOffersItems = [
  {
    id: 1,
    imgurl: "/Trevland/image/slider/usa.png",
    imgalt: "статуя свободы на фоне небоскребов",
    title: "Statue of Liberty",
    country: "New York",
    rating: 4.8,
    duration: "4 Day 5 Nights",
    price: "$450",
  },
  {
    id: 2,
    imgurl: "/Trevland/image/slider/great-wall.png",
    imgalt: "великая китайская стена",
    title: "The Great Wall ",
    country: "China ",
    rating: 4.9,
    duration: "7 Day 8 Nights",
    price: "$850",
  },
  {
    id: 3,
    imgurl: "/Trevland/image/slider/dizin.png",
    imgalt: "иранская деревня",
    title: "Dizin",
    country: "Iran",
    rating: 4.6,
    duration: "5 Day 6 Nights",
    price: "$550",
  },
  {
    id: 4,
    imgurl: "/Trevland/image/slider/sajek.png",
    imgalt: "дом около океана",
    title: "Sajek Valley",
    country: "Bangladesh",
    rating: 4.7,
    duration: "3 Day 4 Nights",
    price: "$400",
  },
  {
    id: 5,
    imgurl: "/Trevland/image/slider/osaka.png",
    imgalt: "замок в Осаке",
    title: "Osaka Castle",
    country: "Japan",
    rating: 4.7,
    duration: "4 Day 5 Nights",
    price: "$700",
  },
  {
    id: 6,
    imgurl: "/Trevland/image/slider/usa.png",
    imgalt: "статуя свободы на фоне небоскребов",
    title: "Statue of Liberty",
    country: "New York",
    rating: 4.8,
    duration: "4 Day 5 Nights",
    price: "$450",
  },
  {
    id: 7,
    imgurl: "/Trevland/image/slider/great-wall.png",
    imgalt: "великая китайская стена",
    title: "The Great Wall ",
    country: "China ",
    rating: 4.9,
    duration: "7 Day 8 Nights",
    price: "$850",
  },
  {
    id: 8,
    imgurl: "/Trevland/image/slider/dizin.png",
    imgalt: "иранская деревня",
    title: "Dizin",
    country: "Iran",
    rating: 4.6,
    duration: "5 Day 6 Nights",
    price: "$550",
  },
  {
    id: 9,
    imgurl: "/Trevland/image/slider/sajek.png",
    imgalt: "дом около океана",
    title: "Sajek Valley",
    country: "Bangladesh",
    rating: 4.7,
    duration: "3 Day 4 Nights",
    price: "$400",
  },
  {
    id: 10,
    imgurl: "/Trevland/image/slider/osaka.png",
    imgalt: "замок в Осаке",
    title: "Osaka Castle",
    country: "Japan",
    rating: 4.7,
    duration: "4 Day 5 Nights",
    price: "$700",
  },
];

export const newsItems = [
  {
    id: 1,
    imgurl: "/Trevland/image/news-banff.png",
    imgalt: "озеро, окруженное с одной стороны горами, с другой лесами",
    title: "Banff National Park",
    text: "Banff National Park lies in the heart of the majestic Rocky Mountains in the province of Alberta, and showcases some of Canada's most beautiful scenery. Turquoise-colored lakes, snow-capped peaks, and glaciers are all easily accessible.",
    link: "@thomasalva_adison",
  },
  {
    id: 2,
    imgurl: "/Trevland/image/news-hirosima.png",
    imgalt: "на берегу реки стоит полуразрушенное здание",
    title: "The Hiroshima Peace!",
    text: "It was formally opened to the public in August that year.",
    link: "@shova_bd88",
  },
  {
    id: 3,
    imgurl: "/Trevland/image/news-faithful.png",
    imgalt: "вид на священный город в Индии",
    title: "The faithful prayers!",
    text: "A major pilgrimage center for Hindus, the holy city.",
    link: "@adem/smith",
  },
  {
    id: 4,
    imgurl: "/Trevland/image/news-waters.png",
    imgalt: "очень красивое озеро, окруженное горами",
    title: "Colourful waters!",
    text: "Forest-driven water and energy cycles are poorly.",
    link: "@jhon7leew",
  },
];
