export const popularItems = [
  {
    id: 1,
    imgurl: "/image/loc-turkey.png",
    imgalt: "Воздушные шары над Каппадокией",
    title: "Istanbul, Turkey",
    text: "Istanbul is a major city in Turkey that straddles Europe. ",
  },
  {
    id: 2,
    imgurl: "/image/loc-korea.png",
    imgalt: "фото Южной Кореи",
    title: "Seoul, South Korea",
    text: "South Korea officially the Republic of Korea is a country in East Asia.",
  },
  {
    id: 3,
    imgurl: "/image/loc-malaysia.png",
    imgalt: "Золотая статуя на фоне гор",
    title: "Kuala Lumpur, malaysia",
    text: "A 272-step long trek leads you to this century.",
  },
];

export const specialOffersItems = [
  {
    id: 1,
    imgurl: "/image/slider/usa.png",
    imgalt: "статуя свободы на фоне небоскребов",
    title: "Statue of Liberty",
    country: "New York",
    rating: 4.8,
    duration: "4 Day 5 Nights",
    price: "$450",
  },
  {
    id: 2,
    imgurl: "/image/slider/great-wall.png",
    imgalt: "великая китайская стена",
    title: "The Great Wall ",
    country: "China ",
    rating: 4.9,
    duration: "7 Day 8 Nights",
    price: "$850",
  },
  {
    id: 3,
    imgurl: "/image/slider/dizin.png",
    imgalt: "иранская деревня",
    title: "Dizin",
    country: "Iran",
    rating: 4.6,
    duration: "5 Day 6 Nights",
    price: "$550",
  },
  {
    id: 4,
    imgurl: "/image/slider/sajek.png",
    imgalt: "дом около океана",
    title: "Sajek Valley",
    country: "Bangladesh",
    rating: 4.7,
    duration: "3 Day 4 Nights",
    price: "$400",
  },
  {
    id: 5,
    imgurl: "/image/slider/osaka.png",
    imgalt: "замок в Осаке",
    title: "Osaka Castle",
    country: "Japan",
    rating: 4.7,
    duration: "4 Day 5 Nights",
    price: "$700",
  },
  {
    id: 6,
    imgurl: "/image/slider/usa.png",
    imgalt: "статуя свободы на фоне небоскребов",
    title: "Statue of Liberty",
    country: "New York",
    rating: 4.8,
    duration: "4 Day 5 Nights",
    price: "$450",
  },
  {
    id: 7,
    imgurl: "/image/slider/great-wall.png",
    imgalt: "великая китайская стена",
    title: "The Great Wall ",
    country: "China ",
    rating: 4.9,
    duration: "7 Day 8 Nights",
    price: "$850",
  },
  {
    id: 8,
    imgurl: "/image/slider/dizin.png",
    imgalt: "иранская деревня",
    title: "Dizin",
    country: "Iran",
    rating: 4.6,
    duration: "5 Day 6 Nights",
    price: "$550",
  },
  {
    id: 9,
    imgurl: "/image/slider/sajek.png",
    imgalt: "дом около океана",
    title: "Sajek Valley",
    country: "Bangladesh",
    rating: 4.7,
    duration: "3 Day 4 Nights",
    price: "$400",
  },
  {
    id: 10,
    imgurl: "/image/slider/osaka.png",
    imgalt: "замок в Осаке",
    title: "Osaka Castle",
    country: "Japan",
    rating: 4.7,
    duration: "4 Day 5 Nights",
    price: "$700",
  },
];
